### ISSUE TITLE
Missing Artifact 2.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by antrix190** [deviceinsight/kafka-health-check#13]
When i try to use version `2.0.0-SNAPSHOT` along with spring-kafka, i get following error message : 
`Missing artifact com.deviceinsight.kafka:kafka-health-check:jar:2.0.0-SNAPSHOT`

Let me know what am I missing here.

**Comment by pvorb** [comment]
The snapshot version is not on Maven Central. You either need to use a stable version or check out the repository and do a `./mvnw install`. This will install the snapshot version to your local Maven repository.

I admit that the README is misleading, though, so I'll leave this issue open until it is fixed.

**Comment by antrix190** [comment]
Alright! I'll close this issue then.

**Comment by pvorb** [comment]
Reopened because of

> so I'll leave this issue open until it is fixed

;-)

**Comment by ezienecker** [comment]
Fixed
