### ISSUE TITLE
Checking multiple brokers

### ISSUE THREAD

**Issue by marcelobp** [deviceinsight/kafka-health-check#15]
Hi all,

Having multiple brokers, using your library, is there any way to check if one of them is down?
Appreciate your help.

Thanks,
Marcelo

**Comment by ezienecker** [comment]
Hi @marcelobp , this depends on which properties are passed to the Helath Check. But yes, in principle it is possible.

When the health check is instantiated, in addition to the Kafka Health specific properties, the Kafka properties used by the service that includes the health check are also passed (if the caller passes them, which it can/should normally do).

https://github.com/deviceinsight/kafka-health-check/blob/develop/src/main/java/com/deviceinsight/kafka/health/KafkaConsumingHealthIndicator.java#L63

Kind Regards

**Comment by ezienecker** [comment]
I’m closing this issue because it has been inactive for a few months. Please reopen if you still encounter this issue.
